[package]
name = "toaserver"
version = "0.1.0"
authors = ["memoryleak47 <memoryleak47@protonmail.ch>"]
edition = "2018"

[dependencies]
toalib = { path = "../toalib" }
serde = "1.0"
serde_derive = "1.0"
bincode = "1.0"
