[package]
name = "toaclient"
version = "0.1.0"
authors = ["memoryleak47 <memoryleak47@protonmail.ch>"]
edition = "2018"

[dependencies]
sfml = "0.14"
toalib = { path = "../toalib" }
lazy_static = "1.0"
font-kit = "0.1.0"
